var x =
  {
    ref: 'refs/heads/master',
    before: 'ba48d24d50799cc08e2ffd366892bbf5fb0e7e75',
    after: 'f704df234853c6fccbb60f57b5f59c2d7f4f31f9',
    created: false,
    deleted: false,
    forced: false,
    base_ref: null,
    compare: 'https://github.com/DanielEgan/wackcoon-device/compare/ba48d24d5079...f704df234853',
    commits:
    [{
      id: 'f704df234853c6fccbb60f57b5f59c2d7f4f31f9',
      tree_id: 'd6e6ae14c37f86d1e68ea105f5d85754412f2262',
      distinct: true,
      message: 'rotate 180, remove timeout, fix typescript thing',
      timestamp: '2016-06-08T12:31:38-07:00',
      url: 'https://github.com/DanielEgan/wackcoon-device/commit/f704df234853c6fccbb60f57b5f59c2d7f4f31f9',
      author: [Object],
      committer: [Object],
      added: [],
      removed: [Object],
      modified: [Object]
    }],
    head_commit:
    {
      id: 'f704df234853c6fccbb60f57b5f59c2d7f4f31f9',
      tree_id: 'd6e6ae14c37f86d1e68ea105f5d85754412f2262',
      distinct: true,
      message: 'rotate 180, remove timeout, fix typescript thing',
      timestamp: '2016-06-08T12:31:38-07:00',
      url: 'https://github.com/DanielEgan/wackcoon-device/commit/f704df234853c6fccbb60f57b5f59c2d7f4f31f9',
      author:
      {
        name: 'Jeremy Foster',
        email: 'jeremy.foster@live.com',
        username: 'codefoster'
      },
      committer:
      {
        name: 'Jeremy Foster',
        email: 'jeremy.foster@live.com',
        username: 'codefoster'
      },
      added: [],
      removed: ['raspicam.d.ts'],
      modified: ['index.js', 'index.js.map', 'index.ts']
    },
    repository:
    {
      id: 60712114,
      name: 'wackcoon-device',
      full_name: 'DanielEgan/wackcoon-device',
      owner: { name: 'DanielEgan', email: 'daniel.egan@live.com' },
      private: false,
      html_url: 'https://github.com/DanielEgan/wackcoon-device',
      description: '',
      fork: false,
      url: 'https://github.com/DanielEgan/wackcoon-device',
      forks_url: 'https://api.github.com/repos/DanielEgan/wackcoon-device/forks',
      keys_url: 'https://api.github.com/repos/DanielEgan/wackcoon-device/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/DanielEgan/wackcoon-device/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/DanielEgan/wackcoon-device/teams',
      hooks_url: 'https://api.github.com/repos/DanielEgan/wackcoon-device/hooks',
      issue_events_url: 'https://api.github.com/repos/DanielEgan/wackcoon-device/issues/events{/number}',
      events_url: 'https://api.github.com/repos/DanielEgan/wackcoon-device/events',
      assignees_url: 'https://api.github.com/repos/DanielEgan/wackcoon-device/assignees{/user}',
      branches_url: 'https://api.github.com/repos/DanielEgan/wackcoon-device/branches{/branch}',
      tags_url: 'https://api.github.com/repos/DanielEgan/wackcoon-device/tags',
      blobs_url: 'https://api.github.com/repos/DanielEgan/wackcoon-device/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/DanielEgan/wackcoon-device/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/DanielEgan/wackcoon-device/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/DanielEgan/wackcoon-device/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/DanielEgan/wackcoon-device/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/DanielEgan/wackcoon-device/languages',
      stargazers_url: 'https://api.github.com/repos/DanielEgan/wackcoon-device/stargazers',
      contributors_url: 'https://api.github.com/repos/DanielEgan/wackcoon-device/contributors',
      subscribers_url: 'https://api.github.com/repos/DanielEgan/wackcoon-device/subscribers',
      subscription_url: 'https://api.github.com/repos/DanielEgan/wackcoon-device/subscription',
      commits_url: 'https://api.github.com/repos/DanielEgan/wackcoon-device/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/DanielEgan/wackcoon-device/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/DanielEgan/wackcoon-device/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/DanielEgan/wackcoon-device/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/DanielEgan/wackcoon-device/contents/{+path}',
      compare_url: 'https://api.github.com/repos/DanielEgan/wackcoon-device/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/DanielEgan/wackcoon-device/merges',
      archive_url: 'https://api.github.com/repos/DanielEgan/wackcoon-device/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/DanielEgan/wackcoon-device/downloads',
      issues_url: 'https://api.github.com/repos/DanielEgan/wackcoon-device/issues{/number}',
      pulls_url: 'https://api.github.com/repos/DanielEgan/wackcoon-device/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/DanielEgan/wackcoon-device/milestones{/number}',
      notifications_url: 'https://api.github.com/repos/DanielEgan/wackcoon-device/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/DanielEgan/wackcoon-device/labels{/name}',
      releases_url: 'https://api.github.com/repos/DanielEgan/wackcoon-device/releases{/id}',
      deployments_url: 'https://api.github.com/repos/DanielEgan/wackcoon-device/deployments',
      created_at: 1465402669,
      updated_at: '2016-06-08T16:26:28Z',
      pushed_at: 1465414305,
      git_url: 'git://github.com/DanielEgan/wackcoon-device.git',
      ssh_url: 'git@github.com:DanielEgan/wackcoon-device.git',
      clone_url: 'https://github.com/DanielEgan/wackcoon-device.git',
      svn_url: 'https://github.com/DanielEgan/wackcoon-device',
      homepage: '',
      size: 8,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'TypeScript',
      has_issues: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      open_issues_count: 0,
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master',
      stargazers: 0,
      master_branch: 'master'
    },
    pusher: { name: 'codefoster', email: 'jeremy.foster@live.com' },
    sender:
    {
      login: 'codefoster',
      id: 1494781,
      avatar_url: 'https://avatars.githubusercontent.com/u/1494781?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/codefoster',
      html_url: 'https://github.com/codefoster',
      followers_url: 'https://api.github.com/users/codefoster/followers',
      following_url: 'https://api.github.com/users/codefoster/following{/other_user}',
      gists_url: 'https://api.github.com/users/codefoster/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/codefoster/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/codefoster/subscriptions',
      organizations_url: 'https://api.github.com/users/codefoster/orgs',
      repos_url: 'https://api.github.com/users/codefoster/repos',
      events_url: 'https://api.github.com/users/codefoster/events{/privacy}',
      received_events_url: 'https://api.github.com/users/codefoster/received_events',
      type: 'User',
      site_admin: false
    }
  }